name: Build all and test

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#on: workflow_dispatch

on:
  push:
    branches:
      - develop
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Local tests"
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      checks: write
      contents: write
      pull-requests: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Apply Spotless
        run: |
          ./gradlew spotlessApply :build-logic:convention:spotlessApply

      - name: Check build-logic
        run: ./gradlew check -p build-logic

      - name: Check Detekt
        run: ./gradlew detekt

      - name: Upload merge detekt
        uses: github/codeql-action/upload-sarif@v3.29.2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif
          category: detekt

      - name: Check Dependency Guard
        id: dependencyguard_verify
        continue-on-error: true
        run: ./gradlew dependencyGuard

      - name: Prevent updating Dependency Guard baselines if this is a fork
        id: checkfork_dependencyguard
        continue-on-error: false
        if: steps.dependencyguard_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "::error::Dependency Guard failed, please update baselines with: ./gradlew dependencyGuardBaseline" && exit 1

        # Runs if previous job failed
      - name: Generate new Dependency Guard baselines if verification failed and it's a PR
        id: dependencyguard_baseline
        if: steps.dependencyguard_verify.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          ./gradlew dependencyGuardBaseline

      - name: Generate coverage reports for Jvm
        run: ./gradlew koverHtmlReportJvm koverXmlReportJvm

      - name: Upload JVM local results (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: local-test-results
          path: '**/build/reports/tests/jvmTest'

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.20.0
        with:
            check_name: Test results
            comment_title: Test results
            large_files: true
            ignore_runs: false
            files: ./**/build/test-results/**/*.xml

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./**/build/test-results/**/*.xml

      - name: Upload local coverage reports (XML + HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          if-no-files-found: error
          compression-level: 1
          overwrite: false
          path: '**/build/reports/kover/'

      - name: Upload coverage
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "app/build/reports/kover/reportJvm.xml"
          verbose: true



      - name: Check lint
        run: ./gradlew lintRelease

      - uses: github/codeql-action/upload-sarif@v3.29.2
        if: success() || failure()
        with:
          sarif_file: app/build/reports/lint-results-release.sarif
          category: lint

      - name: Upload lint reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*.html'

      - name: Push new Spotless Apply if available
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '**/*.kt **/*.kts **/*.xml'
          disable_globbing: true
          commit_message: "🤖 Apply Spotless formatting"

      - name: Push new Dependency Guard baselines if available
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.dependencyguard_baseline.outcome == 'success'
        with:
          file_pattern: '**/dependencies/*.txt'
          disable_globbing: true
          commit_message: "🤖 Updates baselines for Dependency Guard"

