name: Publish Artifacts to Github

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - name: Install GPG
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" | gpg --dearmor > ${HOME}/secring.gpg

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Add Gradle Properties
        env:
          GITHUB_PACKAGES_USER_NAME: ${{ secrets.GH_PACKAGES_USER_NAME }}
          GITHUB_PACKAGES_PASSWORD: ${{ secrets.GH_PACKAGES_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

        run: |
          echo -e "\t" >> gradle.properties
          echo "githubPackagesUsername=${GITHUB_PACKAGES_USER_NAME}" >> gradle.properties
          echo -e "\t" >> gradle.properties
          echo "githubPackagesPassword=${GITHUB_PACKAGES_PASSWORD}" >> gradle.properties
          echo "signing.keyId=${SIGNING_KEY_ID}" >> gradle.properties
          echo -e "\t" >> gradle.properties
          echo "signing.password=${SIGNING_KEY_PASSWORD}" >> gradle.properties
          echo -e "\t" >> gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/secring.gpg" >> gradle.properties

      - name: Set version from tag
        id: version_tag
        run: ./gradlew setVersionFromTag -PnewVersionName=${{ github.ref_name }}

      - name: Publish To GitHub Packages
        run: |
          ./gradlew publishAllPublicationsToGithubPackagesRepository
